spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/air_project?allowPublicKeyRetrieval=true&useSSL=false'
    username: air_user
    password: air_password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

airvisual:
  api:
    endpoint:
      prod: 'https://api.airvisual.com/v2'
  app:
    username: 'Piotr'
    key: 'c41e2a9c-075a-48ce-841a-0407baf3c403'
