spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/air_project?allowPublicKeyRetrieval=true&useSSL=false'
    username: air_user
    password: air_password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

airvisual:
  api:
    endpoint:
      prod: 'https://api.airvisual.com/v2'
  app:
    key: 'c41e2a9c-075a-48ce-841a-0407baf3c403'

airtable:
  api:
    endpoint:
        record: 'https://api.airtable.com/v0'
        meta: 'https://api.airtable.com/v0/meta/bases'
  app:
    token: 'patcSmP0kTcNZM5M0.2b1cb7bb7d3ebe94d1e39d3cb5ace299dba6077e2d708420f1b050842300f8f5'